"""Bespoke Dockerfile / pyproject.toml / package.json for an RDF-Connect build.

Generic RDF-Connect containers ship every processor of every runner,
which is wasteful. This compiler produces a container recipe tailored
to the components actually used in the pipeline:

- The Dockerfile itself is generic and taken verbatim from a
  ``tcs:DockerImageConfig`` attached to ``rdfc:Orchestrator`` in the
  catalog. It only needs to know how to install a ``pyproject.toml``
  and a ``package.json``.
- ``pyproject.toml`` and ``package.json`` are synthesised from the
  ``spdx:Package`` blank nodes reached via
  ``dct:requires`` from every component the pipeline instantiates in
  an RDF-Connect container. Each package carries a
  ``tcs:packageManager`` (``:pip`` / ``:npm``) that routes it to the
  right file.

The three files land under ``rdfc/`` alongside ``pipeline.ttl`` so a
``docker compose ... build: ./rdfc`` picks them up as one bundle.

As a side effect the compiler also patches the ``build:`` key of the
``tcs:DockerComposeConfig`` paired with the ``tcs:DockerImageConfig``
(i.e. attached to the same component) so it points at ``./rdfc``.
That keeps :class:`DockerComposeCompiler` framework-agnostic — it
keeps aggregating whatever compose bodies each domain compiler has
finished shaping, without having to know that RDF-Connect wants a
local build context.
"""

import json

import pandas as pd
from rdflib import Graph, Literal, URIRef
from rdfine import GraphReader, receive_first

from ..base import Compiler
from ..utils import attach_file, extract_config, parse_docker_compose_config

# Path (relative to the generated docker-compose.yml) at which
# ``attach_file`` writes ``Dockerfile`` / ``pyproject.toml`` /
# ``package.json``. Kept next to the compose ``build:`` patch so the
# two stay in sync if the layout ever moves.
_RDFC_BUILD_CONTEXT = "./rdfc"

# Boilerplate for the generated pyproject.toml. Kept as a template
# here because it is compiler-owned semantic knowledge (RDF-Connect
# runners depend on hatchling / uv / direct-url references); the
# per-pipeline part is only the dependency list injected via
# ``{dependencies}``.
_PYPROJECT_TEMPLATE = """\
[project]
name = "rdf-connect-python-resources"
version = "0.0.1"
description = "Python resources for RDF Connect pipelines"
requires-python = "==3.13.*"
license = "MIT"
# Generated by RdfcDockerFileCompiler from spdx:Package annotations in
# the catalog. Local packages are expressed as PEP 508 direct URL
# references via spdx:downloadLocation.
dependencies = [
{dependencies}
]

# Declares that hatchling is to be used - the RDF Connect Python runner depends on this, so do not change
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["resources"]

[tool.hatch.envs.default]
type = "virtual"
path = ".venv"
system-packages = false
installer = "uv"
env-vars = {{ PYTHONPATH = "src" }}

# Allow ``@ file://`` and other direct-url dependency references
[tool.hatch.metadata]
allow-direct-references = true
"""


class RdfcDockerFileCompiler(Compiler):
    """Produce the three files that describe an RDF-Connect container image.

    Attaches, under ``rdfc/``:

    - ``Dockerfile`` — verbatim from the ``tcs:DockerImageConfig``
      reachable from an ``rdfc:Orchestrator`` container.
    - ``pyproject.toml`` — from every ``spdx:Package`` with
      ``tcs:packageManager :pip`` reachable via ``dct:requires``
      from any component that container instantiates.
    - ``package.json`` — same story for ``tcs:packageManager :npm``.

    Also patches the ``build:`` key of the paired
    ``tcs:DockerComposeConfig`` so it points at ``./rdfc`` — the
    directory into which the three files above will be materialised.
    Doing this here rather than in :class:`DockerComposeCompiler`
    keeps the aggregator generic: each framework compiler shapes its
    own compose fragment, then the aggregator merges them.
    """

    def __init__(self, graph: Graph) -> None:
        super().__init__(graph)
        # Intermediate state — populated in ``compile``; declared here
        # so post-run inspection (``gen.compilers[cls].df_packages``)
        # has a stable surface.
        self.df_packages: pd.DataFrame = pd.DataFrame()
        self.dockerfile_body: str = ""
        self.compose_config_id: str = ""

    @classmethod
    def applies_to(cls, graph_reader: GraphReader) -> bool:
        """Triggered when an RDF-Connect container exists and a
        ``tcs:DockerImageConfig`` is attached to ``rdfc:Orchestrator``.

        Both conditions matter: without the container assignment (from
        :class:`PipelineAssembler`) we cannot know which components to
        collect packages for, and without the image config on
        ``rdfc:Orchestrator`` there is no Dockerfile body for this
        compiler to attach. Anchoring on ``rdfc:Orchestrator`` here
        mirrors the SPARQL used in :meth:`extract_dockerfile` and
        :meth:`_patch_paired_compose_build_path`, so a future
        ``tcs:DockerImageConfig`` attached to some other framework's
        component does not spuriously trigger this compiler.
        """
        return not graph_reader.select(
            "?container",
            """
                ?container a tcs:DockerContainer .
                ?container tcs:instantiates rdfc:Orchestrator .
                rdfc:Orchestrator tcs:config ?image_config .
                ?image_config a tcs:DockerImageConfig .
            """,
        ).empty

    def compile(self) -> Graph:
        self.extract_dockerfile()
        self.collect_packages()
        self.attach_rdfc_docker_files()
        return self.output_reader.graph

    def extract_dockerfile(self) -> None:
        """Read the Dockerfile body off the ``tcs:DockerImageConfig`` on
        ``rdfc:Orchestrator``.

        The anchor on ``rdfc:Orchestrator`` is deliberate: this
        compiler owns exactly the RDF-Connect image, and pulling
        image configs by rdf:type alone would silently pick up any
        ``tcs:DockerImageConfig`` a future catalog entry might attach
        to some other framework's component.

        Dispatch through :func:`extract_config` relies on the
        catalog's ``dct:format`` annotation — for a Dockerfile that
        is ``"text/x-dockerfile"``, which produces a raw string body
        (no YAML parsing). If the annotation is wrong or missing,
        ``extract_config`` raises rather than silently mis-parsing.
        """
        config_id = receive_first(
            self.output_reader.select(
                "?config",
                """
                    rdfc:Orchestrator tcs:config ?config .
                    ?config a tcs:DockerImageConfig .
                """,
            )["config"],
        )
        body = extract_config(self.output_reader, config_id)
        if not isinstance(body, str):
            raise TypeError(
                f"tcs:DockerImageConfig {config_id!s} did not yield a string body; "
                "check its dct:format annotation."
            )
        self.dockerfile_body = body

    def collect_packages(self) -> None:
        """One row per ``spdx:Package`` reachable from an rdfc container.

        Deduplicates on ``(name, manager)`` so the same package
        showing up on multiple components does not produce duplicate
        dependency entries — but only when every row agrees on
        ``version``/``download``. Two components requiring genuinely
        different versions of the same package is a modelling
        conflict, not something a "first one wins" dedup should paper
        over silently.
        """
        df = self.output_reader.select(
            "?name ?version ?download ?manager",
            """
                ?container a tcs:DockerContainer .
                ?container tcs:instantiates rdfc:Orchestrator .
                ?container tcs:instantiates ?component .
                ?component dct:requires ?package .
                ?package a spdx:Package .
                ?package spdx:name ?name .
                ?package spdx:suppliedBy ?manager .
                OPTIONAL { ?package spdx:versionInfo ?version . }
                OPTIONAL { ?package spdx:downloadLocation ?download . }
            """,
        )
        if df.empty:
            self.df_packages = df
            return

        df = df.drop_duplicates().reset_index(drop=True)
        conflicting = (
            df.groupby(["name", "manager"])[["version", "download"]]
            .nunique()
            .gt(1)
            .any(axis=1)
        )
        if conflicting.any():
            details = "; ".join(
                f"{name} ({manager})"
                for name, manager in conflicting[conflicting].index
            )
            raise ValueError(
                "Conflicting spdx:versionInfo/spdx:downloadLocation declared "
                f"for the same package across components: {details}. Align "
                "the catalog's spdx:Package declarations before compiling."
            )
        self.df_packages = df.drop_duplicates(subset=["name", "manager"]).reset_index(
            drop=True
        )

    def attach_rdfc_docker_files(self) -> None:
        """Attach Dockerfile/pyproject.toml/package.json under ``rdfc/``
        and patch the paired compose config's ``build:`` path to match.
        """
        self.output_reader = attach_file(
            self.output_reader,
            filename="Dockerfile",
            filepath="rdfc",
            content=self.dockerfile_body,
        )
        self.output_reader = attach_file(
            self.output_reader,
            filename="pyproject.toml",
            filepath="rdfc",
            content=self._render_pyproject(),
        )
        self.output_reader = attach_file(
            self.output_reader,
            filename="package.json",
            filepath="rdfc",
            content=self._render_package_json(),
        )
        self._patch_paired_compose_build_path()

    def _render_pyproject(self) -> str:
        """Fill the pyproject.toml template with the ``:pip`` packages."""
        deps = self._render_pip_dependency_lines()
        formatted = ",\n".join(f'    "{line}"' for line in deps)
        return _PYPROJECT_TEMPLATE.format(dependencies=formatted)

    def _render_pip_dependency_lines(self) -> list[str]:
        """Turn each ``:pip`` row into a PEP 508 dependency string.

        Local packages (those with ``spdx:downloadLocation``) use the
        direct-URL form ``<name> @ <url>``. Everything else uses
        ``<name><version>`` and expects ``version`` to already carry
        an operator (``>=``, ``~=``, ...) — that is a modelling
        constraint on the catalog, not a translation the compiler
        attempts.
        """
        if self.df_packages.empty:
            return []
        pip = self.df_packages.loc[self.df_packages["manager"] == ":pip"]
        lines: list[str] = []
        for _, row in pip.iterrows():
            name = row["name"]
            download = row.get("download")
            version = row.get("version")
            if pd.notna(download):
                lines.append(f"{name} @ {download}")
            elif pd.notna(version):
                lines.append(f"{name}{version}")
            else:
                lines.append(name)
        return sorted(lines)

    def _render_package_json(self) -> str:
        """Emit ``{"dependencies": {name: version, ...}}`` for ``:npm`` rows."""
        deps: dict[str, str] = {}
        if not self.df_packages.empty:
            npm = self.df_packages.loc[self.df_packages["manager"] == ":npm"]
            for _, row in npm.iterrows():
                version = row.get("version")
                deps[row["name"]] = str(version) if pd.notna(version) else "*"
        # Sorted keys give a deterministic file for diff-friendly builds.
        payload = {"dependencies": dict(sorted(deps.items()))}
        return json.dumps(payload, indent=2) + "\n"

    def _patch_paired_compose_build_path(self) -> None:
        """Rewrite ``build:`` on ``rdfc:Orchestrator``'s compose config.

        Called only from :meth:`attach_rdfc_docker_files`, the public
        step that owns it.

        Anchored explicitly on ``rdfc:Orchestrator`` — this compiler
        only ever owns that component's compose fragment. Every
        service body found in the compose config gets ``build`` set
        to ``./rdfc`` — the directory into which the Dockerfile /
        pyproject.toml / package.json are attached above.

        If ``rdfc:Orchestrator`` has no compose config attached
        (i.e. the catalog author omitted it), nothing happens; the
        downstream :class:`DockerComposeCompiler` simply has nothing
        extra to aggregate.

        The rewrite follows the same idiom as
        :class:`SemanticWorksEnvVarCompiler`: strip the existing
        ``tcs:literal`` / ``tcs:embedded`` triples off the config
        node and re-attach a fresh ``tcs:literal`` carrying the
        normalised JSON body. ``DockerComposeCompiler`` re-parses
        that shape without special-casing.
        """
        compose_ids = self.output_reader.select(
            "?compose_config",
            """
                rdfc:Orchestrator tcs:config ?compose_config .
                ?compose_config a tcs:DockerComposeConfig .
            """,
        )["compose_config"].to_list()
        if not compose_ids:
            return
        self.compose_config_id = compose_ids[0]

        normalized = parse_docker_compose_config(
            self.output_reader, self.compose_config_id
        )
        if not normalized.get("services"):
            return
        for service_body in normalized["services"].values():
            service_body["build"] = _RDFC_BUILD_CONTEXT

        new_body = json.dumps(
            self.output_reader.prefix_store.drop(normalized),
        )

        remove_triples = self.output_reader.filter(
            sub=self.compose_config_id, pred=["tcs:literal", "tcs:embedded"]
        ).graph
        self.output_reader = self.output_reader.remove(remove_triples)

        add_triples = GraphReader(
            pd.DataFrame.from_records(
                [
                    {
                        "sub": self.compose_config_id,
                        "pred": "tcs:literal",
                        "obj": new_body,
                        "sub_type": URIRef,
                        "obj_type": Literal,
                    }
                ]
            ),
            self.output_reader.prefix_store,
        ).graph
        self.output_reader = self.output_reader.add(add_triples)
