input:
  adapter:
    name: Ldio:RdfAdapter
  name: Ldio:HttpInPoller
  config:
    cron: '*/10 * * * * *'
    url: https://dishacled-api.azurewebsites.net/api/v1/source-a/current
transformers:
- name: Ldio:SparqlConstructTransformer
  config:
    query: "\n            PREFIX dct: <http://purl.org/dc/terms/> .\n            PREFIX\
      \ prov: <http://www.w3.org/ns/prov#> .\n            CONSTRUCT {\n          \
      \    ?versionedS ?p ?o ;\n                  prov:generatedAtTime ?generatedAtTime\
      \ ;\n                  dct:isVersionOf ?s .\n            } WHERE {\n       \
      \       ?s ?p ?o .\n              BIND(URI(CONCAT(STR(?s), '/', STR(?now)))\
      \ as ?versionedS)\n              BIND (NOW() as ?generatedAtTime)\n        \
      \    }\n          "
outputs:
- name: Ldio:HttpOut
