[project]
name = "rdf-connect-python-resources"
version = "0.0.1"
description = "Python resources for RDF Connect pipelines"
requires-python = "==3.13.*"
license = "MIT"
# For local packages, i.e. those that are not fetched on PyPl, place them in the local_packages folder and list them here. Filepath has to be the full filepath in the docker container.
dependencies = [
    "rdfc-proto>=1.0.0",
    "rdfc-runner>=1.0.0",
    "rdfc_log-processor>=1.0.0",
    "rdfc_http_out @ file:///workspace/pipeline/local_processors/rdfc_http_out"
]

# Declares that hatchling is to be used - the RDF Connect Python runner depends on this, so do not change
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# Not sure what this does, but it works, so do not change 
[tool.hatch.build.targets.wheel]
packages = ["resources"]

# Not sure what these do, but it works, so do not change 
[tool.hatch.envs.default]
type = "virtual"
path = ".venv"
system-packages = false
installer = "uv"
env-vars = { PYTHONPATH = "src" }

# Setting to allow that packages are installed from local filepath rather than public PyPl
[tool.hatch.metadata]
allow-direct-references = true
