services:
  berichtencentrum-deliver-email-service:
    image: lblod/berichtencentrum-deliver-email-service
    environment: {}
    depends_on:
    - identifier
    - triplestore
  ldio-workbench:
    container_name: ldio-workbench
    image: ldes/ldi-orchestrator:2.8.0-SNAPSHOT
    ports:
    - 8080:8080
    depends_on:
    - ldio-pipeline-starter
    - rdfc
  ldio-pipeline-starter:
    image: curlimages/curl
    volumes:
    - ./ldio/config.yml:/pipeline.yml:ro
    command: 'sh -c " sleep 30 && curl -X POST -H ''content-type: application/yaml''
      http://ldio-workbench:8080/admin/api/v1/pipeline --data-binary @/pipeline.yml
      "'
  error-alert:
    image: lblod/loket-error-alert-service:1.0.2
    volumes:
    - ./config/error-alert/:/config/
    environment:
      EMAIL_FROM: mail@threshold-monitoring.com
      EMAIL_TO: firefighters@antwerpen.be
      ERROR_TEMPLATE: /mnt/templates/error.hbs
    depends_on:
    - delta-notifier
    - identifier
    - triplestore
  database:
    image: semtech/sparql-parser:0.0.15
    volumes:
    - ./semantic-works/config/authorization/:/config/
    - ./semantic-works/data/authorization/:/data/
    depends_on:
    - triplestore
  resource:
    image: semtech/mu-cl-resources:1.27.2
    volumes:
    - ./semantic-works/config/resources:/config
    depends_on:
    - database
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
    - ./semantic-works/config/delta:/config/
    depends_on:
    - triplestore
  dispatcher:
    image: semtech/mu-dispatcher:2.1.1
    volumes:
    - ./semantic-works/config/dispatcher:/config
    depends_on:
    - database
    - resource
  identifier:
    image: semtech/mu-identifier:1.11.0
    environment:
      SESSION_COOKIE_SECURE: 'on'
    depends_on:
    - dispatcher
  rdfc:
    container_name: rdfc
    image: rdf-connect:latest
    build: ./rdfc
    volumes:
    - ./rdfc/pipeline.ttl:/workspace/pipeline/pipeline.ttl:ro
    environment:
      LOG_LEVEL: debug
    command: npx rdfc /workspace/pipeline/pipeline.ttl
  triplestore:
    image: redpencil/virtuoso:1.4.0
    environment:
      SPARQL_UPDATE: 'true'
