services:
  rdf-connect:
    container_name: rdf-connect
    image: rdf-connect:latest
    build: ./rdfc
    volumes:
    - ./rdfc/pipeline.ttl:/workspace/pipeline/pipeline.ttl:ro
    environment:
      LOG_LEVEL: debug
    command: npx rdfc /workspace/pipeline/pipeline.ttl
  berichtencentrum-deliver-email-service:
    image: lblod/berichtencentrum-deliver-email-service
    environment:
      EMAIL_CRON_PATTERN: '*/1 * * * * *'
      HOURS_DELIVERING_TIMEOUT: '1'
      MAILFOLDER_URI: http://data.lblod.info/id/mail-folders/2
  ldio-pipeline-starter:
    image: curlimages/curl
    volumes:
    - ./ldio/config.yml:/pipeline.yml:ro
    command: 'sh -c " sleep 30 && curl -X POST -H ''content-type: application/yaml''
      http://ldio-workbench:8080/admin/api/v1/pipeline --data-binary @/pipeline.yml
      "'
  error-alert:
    image: lblod/loket-error-alert-service
    volumes:
    - ./config/error-alert/:/config/
    environment:
      DEBUG: false
      EMAIL_FROM: info@dishacled.com
      EMAIL_TO: everyone@world.com
  ldio-workbench:
    container_name: ldio-workbench
    image: ldes/ldi-orchestrator:2.8.0-SNAPSHOT
    ports:
    - 8080:8080
  virtuoso:
    image: redpencil/virtuoso:1.4.0
    environment:
      SPARQL_UPDATE: 'true'
